rosbag2_performance_benchmarking_publishers:
  ros__parameters:
    publishers:
      publisher_groups: [ "10Mbs_many_frequent_small", "100Mbs_large" ]
      10Mbs_many_frequent_small:
        publishers_count:   500
        topic_root:         "benchmarking_small"
        msg_size_bytes:     100
        msg_count_each:     2000
        rate_hz:            200
      100Mbs_large:
        publishers_count:   1
        topic_root:         "benchmarking_large"
        msg_size_bytes:     10000000
        msg_count_each:     100
        rate_hz:            10
