# Optional path where the new folder for recording will be created. If provided, it will override
# the storage_options.uri provided during construction. Empty by default.
string uri

# Timestamp in the future when to start recording.
# If empty or time in the past, recording starts immediately.
builtin_interfaces/Time start_time
---
# Return code. Returns 1 when recording is already running or in case of error, otherwise 0.
int32 return_code
# Error string. Empty if no error occurred.
string error_string
