# Timestamp in the future when to resume recording.
# If empty or time in the past, resumes recording immediately.
# Note: The resume_time is not supported by player and shall be set to zero when using Resume
# request with player.
builtin_interfaces/Time resume_time
---
