import collections.abc
import datetime
import rosbag2_py._storage
import typing
from _typeshed import Incomplete
from typing import Any, ClassVar, overload

class MessageOrder:
    __members__: ClassVar[dict] = ...  # read-only
    RECEIVED_TIMESTAMP: ClassVar[MessageOrder] = ...
    SENT_TIMESTAMP: ClassVar[MessageOrder] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: typing.SupportsInt) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class PlayOptions:
    actions_to_filter: list[str]
    clock_publish_frequency: float
    clock_publish_on_topic_publish: bool
    clock_topics: list[str]
    delay: float
    disable_keyboard_controls: bool
    disable_loan_message: bool
    exclude_actions_to_filter: list[str]
    exclude_regex_to_filter: str
    exclude_service_events_to_filter: list[str]
    exclude_topics_to_filter: list[str]
    loop: bool
    message_order: Incomplete
    node_prefix: str
    playback_duration: float
    playback_until_timestamp: int
    progress_bar_separation_lines: int
    progress_bar_update_rate: int
    publish_service_requests: bool
    rate: float
    read_ahead_queue_size: int
    regex_to_filter: str
    send_actions_as_client: bool
    service_requests_source: Incomplete
    services_to_filter: list[str]
    start_offset: float
    start_paused: bool
    topic_qos_profile_overrides: dict
    topic_remapping_options: list[str]
    topics_to_filter: list[str]
    wait_acked_timeout: int
    def __init__(self) -> None: ...

class Player:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, log_level: str) -> None: ...
    @overload
    def __init__(self, storage_options: rosbag2_py._storage.StorageOptions, play_options: PlayOptions, log_level: str = ..., node_name: str = ...) -> None: ...
    @overload
    def __init__(self, storage_options: collections.abc.Sequence[rosbag2_py._storage.StorageOptions], play_options: PlayOptions, log_level: str = ..., node_name: str = ...) -> None: ...
    @overload
    def burst(self, num_messages: typing.SupportsInt) -> int: ...
    @overload
    def burst(self, constsize_t) -> Any: ...
    @overload
    def burst(self, storage_options: rosbag2_py._storage.StorageOptions, play_options: PlayOptions, num_messages: typing.SupportsInt) -> None: ...
    @overload
    def burst(self, num_messages) -> Any: ...
    @staticmethod
    def cancel() -> None: ...
    def get_playback_duration(self) -> int: ...
    def get_starting_time(self) -> int: ...
    def is_paused(self) -> bool: ...
    def pause(self) -> None: ...
    @overload
    def play(self) -> None: ...
    @overload
    def play(self, storage_options: rosbag2_py._storage.StorageOptions, play_options: PlayOptions) -> None: ...
    @overload
    def play(self) -> Any: ...
    @overload
    def play(self, storage_options: collections.abc.Sequence[rosbag2_py._storage.StorageOptions], play_options: PlayOptions) -> None: ...
    @overload
    def play(self) -> Any: ...
    def play_next(self) -> bool: ...
    def resume(self) -> None: ...
    def seek(self, time_point: typing.SupportsInt) -> None: ...
    def start_spin(self) -> None: ...
    def stop(self) -> None: ...
    def stop_spin(self) -> None: ...
    def wait_for_playback_to_finish(self, timeout: typing.SupportsFloat = ...) -> bool: ...
    def wait_for_playback_to_finish_exclusively(self, timeout: typing.SupportsFloat = ...) -> bool: ...
    def wait_for_playback_to_start(self, timeout: typing.SupportsFloat = ...) -> bool: ...
    def wait_for_playback_to_start_exclusively(self, timeout: typing.SupportsFloat = ...) -> bool: ...

class RecordOptions:
    actions: list[str]
    all_actions: bool
    all_services: bool
    all_topics: bool
    compression_format: str
    compression_mode: str
    compression_queue_size: int
    compression_threads: int
    compression_threads_priority: int
    disable_keyboard_controls: bool
    exclude_actions: list[str]
    exclude_regex: str
    exclude_service_events: list[str]
    exclude_topic_types: list[str]
    exclude_topics: list[str]
    ignore_leaf_topics: bool
    include_hidden_topics: bool
    include_unpublished_topics: bool
    input_serialization_format: str
    is_discovery_disabled: bool
    node_prefix: str
    output_serialization_format: str
    regex: str
    repeat_all_transient_local_depth: int
    repeat_transient_local_messages: dict[str, int]
    rmw_serialization_format: str
    services: list[str]
    start_paused: bool
    static_topics_uri: str
    statistics_max_publishing_rate: float
    topic_polling_interval: datetime.timedelta
    topic_qos_profile_overrides: dict
    topic_types: list[str]
    topics: list[str]
    use_sim_time: bool
    def __init__(self) -> None: ...

class Recorder:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg: str) -> None: ...
    @overload
    def __init__(self, storage_options: rosbag2_py._storage.StorageOptions, record_options: RecordOptions, log_level: str = ..., node_name: str = ...) -> None: ...
    @staticmethod
    def cancel() -> None: ...
    def is_paused(self) -> bool: ...
    def pause(self) -> None: ...
    @overload
    def record(self) -> None: ...
    @overload
    def record(self) -> Any: ...
    @overload
    def record(self, storage_options: rosbag2_py._storage.StorageOptions, record_options: RecordOptions, node_name: str = ...) -> None: ...
    @overload
    def record(self) -> Any: ...
    def resume(self) -> None: ...
    def start_spin(self) -> None: ...
    def stop(self) -> None: ...
    def stop_spin(self) -> None: ...

class ServiceRequestsSource:
    __members__: ClassVar[dict] = ...  # read-only
    CLIENT_INTROSPECTION: ClassVar[ServiceRequestsSource] = ...
    SERVICE_INTROSPECTION: ClassVar[ServiceRequestsSource] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: typing.SupportsInt) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

def bag_rewrite(input_options: collections.abc.Sequence[rosbag2_py._storage.StorageOptions], input_config_file: str, output_config_file: str) -> None: ...
