import rosbag2_py._compression_options
import rosbag2_py._storage
import typing
from typing import overload

class SequentialCompressionWriter:
    def __init__(self, arg0: rosbag2_py._compression_options.CompressionOptions) -> None: ...
    def create_topic(self, arg0: rosbag2_py._storage.TopicMetadata) -> None: ...
    def open(self, arg0: rosbag2_py._storage.StorageOptions, arg1: rosbag2_py._storage.ConverterOptions) -> None: ...
    def remove_topic(self, arg0: rosbag2_py._storage.TopicMetadata) -> None: ...
    def split_bagfile(self) -> None: ...
    def take_snapshot(self) -> bool: ...
    @overload
    def write(self, topic_name: str, message: str, time_stamp: typing.SupportsInt, sequence_number: typing.SupportsInt = ...) -> None: ...
    @overload
    def write(self, topic_name: str, message: str, recv_timestamp: typing.SupportsInt, send_timestamp: typing.SupportsInt, sequence_number: typing.SupportsInt = ...) -> None: ...

class SequentialWriter:
    def __init__(self) -> None: ...
    def close(self) -> None: ...
    def create_topic(self, arg0: rosbag2_py._storage.TopicMetadata) -> None: ...
    def open(self, arg0: rosbag2_py._storage.StorageOptions, arg1: rosbag2_py._storage.ConverterOptions) -> None: ...
    def remove_topic(self, arg0: rosbag2_py._storage.TopicMetadata) -> None: ...
    def split_bagfile(self) -> None: ...
    def take_snapshot(self) -> bool: ...
    @overload
    def write(self, topic_name: str, message: str, time_stamp: typing.SupportsInt, sequence_number: typing.SupportsInt = ...) -> None: ...
    @overload
    def write(self, topic_name: str, message: str, recv_timestamp: typing.SupportsInt, send_timestamp: typing.SupportsInt, sequence_number: typing.SupportsInt = ...) -> None: ...

def get_registered_compressors() -> set[str]: ...
def get_registered_serializers() -> set[str]: ...
def get_registered_writers() -> set[str]: ...
