raport_dir: "~/.ros/raports"
rosbag:
    polling_interval: 10
benchmark:
    id: 0
    tag: "bench1"
    name: "Bench test"
    overwrite_existing: true
    monitor_frequency: 10
workers:
    - image:
        name: "camera_low"
        topic: "camera_low"
        instances: 4
        delay: 1000
        max_count: 100
        dimensions: 1024
        dt: 100
    - image:
        name: "camera_high"
        topic: "camera_high"
        instances: 1
        delay: 1000
        max_count: 100
        dimensions: 1024
        dt: 100
    - pointcloud2:
        name: "lidar"
        topic: "lidar"
        instances: 1
        delay: 1000
        max_count: 100
        size: 100000
        dt: 100