raport_dir: "~/.ros/raports"
rosbag:
    polling_interval: 10
benchmark:
    id: 0
    tag: "bench1"
    name: "Bench test"
    overwrite_existing: true
workers:
    - image:
        name: "camera1"
        topic: "camera1"
        delay: 1000
        max_count: 100
        dimensions: 1024
        dt: 100
    - image:
        name: "camera2"
        topic: "camera2"
        delay: 1000
        max_count: 10
        dimensions: 1024
        dt: 200
    - pointcloud2:
        name: "lidar1"
        topic: "lidar1"
        delay: 10
        max_count: 10
        size: 100000
        dt: 10