raport_dir: "~/.ros/raports"
rosbag:
    args: 
        - "--max-cache-size 1"
benchmark:
    id: 0
    tag: "voyager_1000_1"
    name: "1000KB with 1 topic"
    overwrite_existing: true
    monitor_frequency: 10
workers:
    - bytearray:
        name: "voy"
        topic: "voy"
        instances: 1
        same_topic: false
        delay: 1000
        max_count: 1000
        size: 1000000
        frequency: 100