raport_dir: "~/.ros/raports"
rosbag:
    args:
        - "--max-cache-size 1"
benchmark:
    id: 0
    tag: "voyager_1_1000"
    name: "1KB with 1000 topics"
    overwrite_existing: true
    monitor_frequency: 10
workers:
    - bytearray:
        name: "voy"
        topic: "voy"
        instances: 1000
        same_topic: false
        delay: 1000
        max_count: 1000
        size: 1000
        frequency: 100