//
// Created by allabana on 1/14/20.
//

#ifndef ROSBAG2_COMPRESSION_COMPRESSION_OPTIONS_HPP
#define ROSBAG2_COMPRESSION_COMPRESSION_OPTIONS_HPP

#endif //ROSBAG2_COMPRESSION_COMPRESSION_OPTIONS_HPP
